[package]
name = "sond-bevy-enum-components"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace]
members = ["macros"]

[dependencies]
macros = { package = "sond-bevy-enum-components-macros", path = "macros" }
bevy_ecs = { version = "0.9.0-dev", path = "../bevy/crates/bevy_ecs" }

[dev-dependencies]
sond-bevy-enum-components = { version = "0.1.0", path = "." }
bevy = { version = "0.9.0-dev", path = "../bevy", default-features = false }
